Hello-user
Atikingi/skypro-jsb-hw pull request #21
Opened 2022-05-17 17:39 UTC by Atikingi

Сделано первое задание седьмой домашней работы https://skyengpublic.notion.site/3-7-1-5999fbb4f86d41a5b5a9a70f051cadaehttps://skyengpublic.notion.site/3-7-1-5999fbb4f86d41a5b5a9a70f051cadae

Добавлена кнопка, написана логика по замене элементов.

2022-05-19 07:25 UTC, mrerberg requested changes

2022-05-19 07:25 UTC, mrerberg commented on hello-user/script.js
> +    const target = event.target;
Отделяй пробелами смысловые блоки кода

```js
 const target = event.target;

    target.remove();
    
    const newElem = document.createElement('h1');
    newElem.textContent = 'Привет, пользователь!';
    
    box.appendChild(newElem);
```

2022-05-19 08:33 UTC, Atikingi commented on hello-user/script.js
> +    const target = event.target;
Исправлено

2022-05-20 07:17 UTC, mrerberg approved these changes

2022-05-20 07:17 UTC, mrerberg commented on hello-user/script.js
> +    newElem.textContent = 'Привет, пользователь!';
Если что, я не говорю делать прям как я сделала. Просто имей в виду этот подход, разбиение кусков кода по вертикали

2022-05-20 07:21 UTC, Atikingi commented on hello-user/script.js
> +    newElem.textContent = 'Привет, пользователь!';
Но по сути так и получилось логически разбить

2022-05-20 07:23 UTC, merged