Neat-hello-user
Atikingi/skypro-jsb-hw pull request #22
Opened 2022-05-17 17:58 UTC by Atikingi

Сделано второе задание седьмой домашней работы https://skyengpublic.notion.site/3-7-1-5999fbb4f86d41a5b5a9a70f051cadaehttps://skyengpublic.notion.site/3-7-1-5999fbb4f86d41a5b5a9a70f051cadae

Добавлены 3 контейнера и 3 кнопки в них с одним классом. На кажду кнопку подписано событие. По итогу в первом задании почти уже сделал второе, заменил только строчку, где указываю какому элементу назначить ребенка.

2022-05-19 07:24 UTC, mrerberg requested changes

2022-05-19 07:24 UTC, mrerberg commented on neat-hello-user/script.js
> +    const target = event.target;
```js
const { target } = event;
```

Деструкторизация, мать ее

2022-05-19 08:17 UTC, Atikingi commented on neat-hello-user/script.js
> +    const target = event.target;
Исправлено

2022-05-20 07:16 UTC, mrerberg approved these changes

2022-05-20 07:16 UTC, mrerberg commented on neat-hello-user/style.css
> +    width: 33.3333333vw;
Прям не округляется, да?)

2022-05-20 07:20 UTC, Atikingi commented on neat-hello-user/style.css
> +    width: 33.3333333vw;
У меня в памяти, что учили столько троек писать XD

2022-05-20 08:01 UTC, merged