Gender equality
Atikingi/skypro-jsb-hw pull request #30
Opened 2022-05-24 18:24 UTC by Atikingi

Сделано четвертое задание девятой домашней работы https://skyengpublic.notion.site/3-9-1-52f777a4281c445ca222dd7e9c62310a
Добавлена логика проверки radiobutton'ов.

2022-05-25 08:50 UTC, mrerberg requested changes

2022-05-25 08:50 UTC, mrerberg commented on gender-equality/script.js
> +      if (radioValue.checked && radioValue.value === 'men') {
Чтобы не дублировать данную проверку, можно просто сделать выше условие

```js
if(!radioValue.checked) return;
```

2022-05-25 08:50 UTC, mrerberg commented on gender-equality/script.js
> +        errorMessage.textContent = `Мужчинам вход запрещен`;
Эту строку и строку ниже можно вынести в отдельную функцию) И передавать сообщение в виде аргумента

2022-05-25 10:16 UTC, Atikingi commented on gender-equality/script.js
> +      if (radioValue.checked && radioValue.value === 'men') {
Исправил

2022-05-25 10:16 UTC, Atikingi commented on gender-equality/script.js
> +        errorMessage.textContent = `Мужчинам вход запрещен`;
Исправил

2022-05-25 18:14 UTC, mrerberg requested changes

2022-05-25 18:14 UTC, mrerberg commented on gender-equality/script.js
> +      const checkGender = (message) => {
Скорее, не проверяет, а показывает ошибку

2022-05-31 08:28 UTC, Atikingi commented on gender-equality/script.js
> +      const checkGender = (message) => {
Исправил

2022-05-31 08:28 UTC, merged