Pin coder
Atikingi/skypro-jsb-hw pull request #33
Opened 2022-06-04 18:49 UTC by Atikingi

Сделано задание 11-12 домашних работ https://skyengpublic.notion.site/3-11-3-12-e89eae39de0343d3a7ee1eced0d58cb2.
Создан функционал по вводу пин-кода.
1 экран - запоминает пин-код. Функционал:
- ввод с виртуальной или обычной клавиатуры 
- ограничение на ввод всего кроме цифр
- сохранение происходит в localStorage
- лимит на 6 цифр
2 экран - принимает пин-код. Функционал:
- полей генерируется столько, сколько длина пин-кода
- ввод с виртуальной или обычной клавиатуры
- перевод фокуса на соседний инпут при добавлении значения
- перевод на предыдущий инпут при использовании удаления через backspace
- сверка пин-кода с тем, что хранится в localStorage и вывод popup сообщения
- при вставке в любой инпут вставляется с нулевого инпута и до конца 
- кнопка очищения localStorage

2022-06-05 10:45 UTC, mrerberg requested changes

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +class pinCode {
Классы пишутся с большой буквы

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +    if (!(element instanceof HTMLElement)) {
Это я бы вынес в отдельную функцию, например, validateInput/validateArguments/validateProps

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +  constructor(element) {
У тебя офигительных размеров конструктор, это усложняет понимание класса очень. Вполне возможно, тебе следует разбить 1 класс на несколько классов. Желательно, чтобы 1 класс выполнял одну и только 1 логику.

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +      return event.which !== 32;
Данный [способ](https://developer.mozilla.org/ru/docs/Web/API/UIEvent/which) устаревший, deprecated. Стоит через свойство `code` определять клавишу

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +    this.pinCodeKeys.forEach((key) => {
Как вариант, можно не на каждую клавишу отдельно вешать событие, а воспользоваться [всплытием](https://learn.javascript.ru/event-bubbling)

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +    this.pinCodeInput.value.length < 6
[6](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))

2022-06-05 10:45 UTC, mrerberg commented on pin-coder/src/script.js
> +    this.pinCodeInput.value.length < 6
По ссылке есть материал, поймешь сразу, о чем я

2022-06-05 14:29 UTC, Atikingi commented on pin-coder/src/script.js
> +class pinCode {
Исправил

2022-06-05 18:01 UTC, Atikingi commented on pin-coder/src/script.js
> +class pinCode {
Исправил

2022-06-05 18:01 UTC, Atikingi commented on pin-coder/src/script.js
> +    if (!(element instanceof HTMLElement)) {
Исправил

2022-06-05 18:01 UTC, Atikingi commented on pin-coder/src/script.js
> +  constructor(element) {
Исправил

2022-06-05 18:01 UTC, Atikingi commented on pin-coder/src/script.js
> +      return event.which !== 32;
Исправил

2022-06-05 18:01 UTC, Atikingi commented on pin-coder/src/script.js
> +    this.pinCodeKeys.forEach((key) => {
Исправил

2022-06-05 18:01 UTC, Atikingi commented on pin-coder/src/script.js
> +    this.pinCodeInput.value.length < 6
Исправил=)

2022-06-06 08:41 UTC, mrerberg commented on pin-coder/src/classes.js
> +function ValidateProps(props) {
Эту функцию следует сделать внутренним методом класса. Это нормально, когда у класса есть метод для валидации

2022-06-06 09:28 UTC, Atikingi commented on pin-coder/src/classes.js
> +function ValidateProps(props) {
Исправил

2022-06-06 15:55 UTC, mrerberg requested changes

2022-06-06 15:55 UTC, mrerberg commented on pin-coder/src/classes.js
> +    this.wrapper = document.querySelector('.container');
Рекомендую не завязывать логику на классах. Классы слишком изменчивы. Завязывайся лучше на id/дата атрибуты

2022-06-06 15:55 UTC, mrerberg commented on pin-coder/src/classes.js
> +class PinCodeKeyboard extends PinCode {
extends используют обычно, когда у тебя есть общий класс, абстрактный, а ты из него клепаешь однотипных/похожих потомков. Кажется, тут не этот случай.

Или если ты создал единый интерфейс (не UI)/контракт и его пытаешься имплементировать

2022-06-06 21:24 UTC, Atikingi commented on pin-coder/src/classes.js
> +class PinCodeKeyboard extends PinCode {
Избавился

2022-06-06 21:24 UTC, Atikingi commented on pin-coder/src/classes.js
> +    this.wrapper = document.querySelector('.container');
Добавил только для container

2022-06-08 08:32 UTC, mrerberg commented on pin-coder/old/classes-old.js
> +function ValidateProps(props) {
У каждого класса могут быть свои пропсы. Если валидируешь их, то лучше в рамках класса пусть живет данная функция, как его метод

2022-06-08 09:20 UTC, mrerberg requested changes

2022-06-08 09:20 UTC, mrerberg commented on pin-coder/src/pin-code-create.js
> +    this.pinCodeSave.addEventListener('click', (event) => {
Я бы упрятал это в отдельную функцию init event или что-то такое, чтобы не раздувать конструктор

2022-06-08 09:20 UTC, mrerberg commented on pin-coder/src/pin-code-create.js
> +      this.element.querySelectorAll('.pin-code__accept-wrapper').forEach((node) => {
В отдельный метод

2022-06-08 09:20 UTC, mrerberg commented on pin-coder/src/pin-code-inner.js
> +    this.template = [
Можно template хранить в константе и просто импортировать ее и сеттить

this.template = TEMPLATE

2022-06-08 09:20 UTC, mrerberg commented on pin-coder/src/pin-code-inner.js
> +    this.pinCodeKeyboard.addEventListener('click', (event) => {
Желательно в отдельный метод

2022-06-08 09:20 UTC, mrerberg commented on pin-coder/src/pin-code-validate.js
> +  clg() {
Нужен?

2022-06-08 10:02 UTC, Atikingi commented on pin-coder/src/pin-code-create.js
> +    this.pinCodeSave.addEventListener('click', (event) => {
Перенес в метод класса вместе с методом clear

2022-06-08 10:05 UTC, Atikingi commented on pin-coder/src/pin-code-create.js
> +      this.element.querySelectorAll('.pin-code__accept-wrapper').forEach((node) => {
Вынес в removeInnerInputs(element)

2022-06-08 10:10 UTC, Atikingi commented on pin-coder/src/pin-code-inner.js
> +    this.pinCodeKeyboard.addEventListener('click', (event) => {
Вынес в keyboardEvent(keyboard)

2022-06-08 10:10 UTC, Atikingi commented on pin-coder/src/pin-code-validate.js
> +  clg() {
Просто поздоровался =) Удалил

2022-06-08 14:45 UTC, Atikingi commented on pin-coder/src/pin-code-inner.js
> +    this.template = [
Не получится вынести, т.к. завязка на функции

2022-06-09 08:01 UTC, mrerberg approved these changes

2022-06-09 08:06 UTC, merged