Weather
Atikingi/skypro-jsb-hw pull request #39
Opened 2022-06-24 14:37 UTC by Atikingi

Сделано второе задание 15 домашней работы https://skyengpublic.notion.site/3-15-API-1-9411e36ec7a24d069814d1be30ded850

Добавлена логика получения погоды из API, кнопка определения текущего местоположения, саджест для поиска городов.

2022-06-26 13:37 UTC, mrerberg requested changes

2022-06-26 13:37 UTC, mrerberg commented on weather/index.html
> +<html lang="en">
Сайт на русском?

2022-06-26 13:37 UTC, mrerberg commented on weather/index.html
> +          <img src="" alt="weather" class="weather__icon" width="90" />
Alt мало говорящий

2022-06-26 13:37 UTC, mrerberg commented on weather/src/current-weather.js
> +      //   url: '/weather/src/stubs/moscow.json',
Мертвый код?

2022-06-26 13:37 UTC, mrerberg commented on weather/src/current-weather.js
> +        let latitude = data.coords.latitude;
Может через деструкторизацию?

2022-06-26 13:37 UTC, mrerberg commented on weather/src/current-weather.js
> +          console.log('некорректный город');
В данном случае подошел бы алерт, чтобы не только разрабы поняли, что есть ошибка)

2022-06-26 13:37 UTC, mrerberg commented on weather/src/suggest.js
> +    new CurrentWeather();
А почему виджет в погодой инициализируется в классе Suggest? Хвост управляет собакой?

2022-06-26 14:01 UTC, Atikingi commented on weather/index.html
> +<html lang="en">
Исправил

2022-06-26 14:02 UTC, Atikingi commented on weather/index.html
> +          <img src="" alt="weather" class="weather__icon" width="90" />
Исправил

2022-06-26 14:04 UTC, Atikingi commented on weather/src/current-weather.js
> +      //   url: '/weather/src/stubs/moscow.json',
Исправил

2022-06-26 14:05 UTC, Atikingi commented on weather/src/current-weather.js
> +          console.log('некорректный город');
Исправил

2022-06-26 14:06 UTC, Atikingi commented on weather/src/current-weather.js
> +        let latitude = data.coords.latitude;
Исправил

2022-06-26 14:24 UTC, Atikingi commented on weather/src/suggest.js
> +    new CurrentWeather();
Вынес создание класса, но оставил при клике на город из подсказки

2022-06-27 07:54 UTC, mrerberg requested changes

2022-06-27 07:54 UTC, mrerberg commented on weather/src/suggest.js
> +    this.suggest = document.querySelector('.suggest__popup');
Я все же рекомендую работать лучше с id/data атрибутами, когда речь идет о логике

2022-06-27 07:54 UTC, mrerberg commented on weather/src/current-weather.js
> +export default class CurrentWeather {
Если совсем упарываться, я бы сделал 2 класса: 1 с чисто данными (загрузка, отдача данных на рендер, возвращение ошибки), второй чисто работа с ui (рендер)

2022-06-27 07:54 UTC, mrerberg commented on weather/src/current-weather.js
> +        limit: 1,
1 - магическое число, есть смысл вынести в переменную

2022-06-27 07:54 UTC, mrerberg commented on weather/src/current-weather.js
> +          this.lat = data[0].lat;
Деструкторизация?

2022-06-27 07:54 UTC, mrerberg commented on weather/src/current-weather.js
> +        if (data[0]) {
**data[0]**

Я бы вынес это в переменную, чтобы дать контекст/описание

2022-06-27 08:51 UTC, Atikingi commented on weather/src/current-weather.js
> +        limit: 1,
Исправил

2022-06-27 09:15 UTC, Atikingi commented on weather/src/current-weather.js
> +          this.lat = data[0].lat;
исправил

2022-06-27 09:15 UTC, Atikingi commented on weather/src/current-weather.js
> +        if (data[0]) {
исправил

2022-06-27 17:25 UTC, Atikingi commented on weather/src/suggest.js
> +    this.suggest = document.querySelector('.suggest__popup');
Исправил

2022-06-27 17:25 UTC, Atikingi commented on weather/src/current-weather.js
> +export default class CurrentWeather {
Упаролся=)

2022-06-28 07:21 UTC, mrerberg requested changes

2022-06-28 07:21 UTC, mrerberg commented on weather/src/api-data.js
> +    this.APP_ID = '9a3ad09b825a06c0667adeea7504e7c6';
В целом можно и не в конструкторе присвоить, а сразу в свойства класса.

```
export default class DataAPIWeather {
  APP_ID = '9a3ad09b825a06c0667adeea7504e7c6';
```

2022-06-28 07:21 UTC, mrerberg commented on weather/src/api-data.js
> +        const responseCityObject = data[0];
const [responseCityObject] = data;

2022-06-28 07:21 UTC, mrerberg commented on weather/src/api-data.js
> +    const API_URL = 'http://api.openweathermap.org/geo/1.0/direct';
`http://api.openweathermap.org` есть смысл вынести в свойства класса как дефолтный апи урл

2022-06-28 07:21 UTC, mrerberg commented on weather/src/current-weather.js
> +    this.API_DATA = new DataAPIWeather();
Просто api, можно не константой и без data

2022-06-28 07:21 UTC, mrerberg commented on weather/src/current-weather.js
> +    this.API_DATA = new DataAPIWeather();
или weatherApi

2022-06-28 07:27 UTC, Atikingi commented on weather/src/api-data.js
> +        const responseCityObject = data[0];
Исправил

2022-06-28 07:39 UTC, Atikingi commented on weather/src/api-data.js
> +    this.APP_ID = '9a3ad09b825a06c0667adeea7504e7c6';
Исправил

2022-06-28 07:39 UTC, Atikingi commented on weather/src/api-data.js
> +    const API_URL = 'http://api.openweathermap.org/geo/1.0/direct';
Исправил

2022-06-28 07:39 UTC, Atikingi commented on weather/src/current-weather.js
> +    this.API_DATA = new DataAPIWeather();
Исправил

2022-06-29 07:52 UTC, mrerberg approved these changes

2022-06-29 09:06 UTC, merged